version: '3'

services:
  pg:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - '.postgresql/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword